language: rust
rust:
  - 1.12.0
  - beta
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ispell aspell aspell-en aspell-fr
matrix:
  allow_failures:
    - rust: nightly
